#log4j.rootCategory = INFO, CA, FA
log4j.rootCategory =ALL,CA,FA
# No log for these packages
log4j.category.org.apache.struts = OFF
log4j.category.org.apache.commons = OFF

# Set options for Fileappender named FA
#log4j.appender.FA = org.apache.log4j.FileAppender
log4j.appender.FA.Threshold=INFO
log4j.appender.FA = org.apache.log4j.RollingFileAppender
log4j.appender.FA.File = ${user.home}/TAN5Gescom/log/tan5gescom.log
log4j.appender.FA.Append = true
log4j.appender.FA.layout = org.apache.log4j.PatternLayout
log4j.appender.FA.layout.ConversionPattern = %d{ISO8601} %-5p %-40.40C %-15.15M %m (%F : %L) %n
log4j.appender.FA.MaxFileSize=500KB
log4j.appender.FA.MaxBackupIndex=3


# Set options for Consoleappender named CA
log4j.appender.CA = org.apache.log4j.ConsoleAppender
log4j.appender.CA.layout = org.apache.log4j.PatternLayout
log4j.appender.CA.layout.ConversionPattern = %d{ISO8601} %-5p %-40.40C %-15.15M %m%n

rem log4j.appender.A1.MaxFileSize=100KB
rem log4j.appender.S1.MaxBackupIndex=3

log4j.category.org.apache.axis=OFF
log4j.category.com.ozziefix=OFF
log4j.category.GUI.model=OFF


